### ISSUE TITLE
Similar issue over here

### ISSUE THREAD

**Issue by benmcnix** [conema/monterail-fulldark#1]
Hey there @conema : since you were so quick & helpful on the other Issue, I thought I'd test out this theme for you on MacOS. Looks like a similar issue occurs on this one:

![Mouseover](https://user-images.githubusercontent.com/5635267/44674900-8c8d8780-a9f4-11e8-8deb-f98a16f75715.png)

I can only read the message that I hover over.

**Comment by conema** [comment]
I thank you very much for your help! Let me know if this resolve the issue:
[fd_mac.zip](https://github.com/conema/monterail-fulldark/files/2325061/fd_mac.zip)

PS: thank you for your kind words in the review

**Comment by conema** [comment]
Let me know if it works now 🤞 

[fd_mac.zip](https://github.com/conema/monterail-fulldark/files/2325191/fd_mac.zip)

**Comment by benmcnix** [comment]
Perfect!

![Screenshot](https://user-images.githubusercontent.com/5635267/44679387-74236a00-aa00-11e8-8f61-a0b28815b4a7.png)

FYI... not sure if it's the same on other platforms, but I tried not renaming the zip to xpi this time. Thunderbird let me install from the zip file with no problem. I did have to do the install - delete file - restart - install - restart action to get it to work, but renaming was not necessary.

I'll leave you alone today, but will let you know if I run across something else in the future ;)

**Comment by conema** [comment]
Oh, good to know, I think that in Windows only ".xpi" files are shown. An really useful LPT is that in development you can not do the "install - delete file - restart - install - restart" action, you can directly copy the new files into the "MonterailFullDark@conema.me.xpi", located in the "extensions" dir, with a zip tool. Hope that this will help you, thanks again for your precious help!
