### ISSUE TITLE
Unreadable From, Subject etc. fields when e-mail is opened in new window

### ISSUE THREAD

**Issue by VforMaverick** [conema/monterail-fulldark#10]
After double-clicking received e-mail to open it in new window, fields such as "From", "Subject", "Respond to", "To" are written in white color on very bright background and are completely unreadable, as seen below: 
![invisible1](https://user-images.githubusercontent.com/44070422/46827822-ee823080-cd99-11e8-8057-a0e3be4ae3aa.png)

Only after hovering mouse cursor they are highlighted (background around text changes to blue), as seen below:
![invisible2](https://user-images.githubusercontent.com/44070422/46827884-12de0d00-cd9a-11e8-9e22-36574f5119d0.png)

Windows 10 Home, Thunderbird v60.2.1 (32-bit)

**Comment by conema** [comment]
Hi @VforMaverick, thanks for your reporting, the PR with the fix is ready (#11).  The update via TB addons should be online in a few day.

I'll close this issue when the update will be released.

**Comment by VforMaverick** [comment]
Cool, thanks for the info! :) Btw, the theme is beautiful! Found it recently, just after the latest TB update, when TTDeepDark started working really sluggish and I had to abandon it.

**Comment by conema** [comment]
Update is out, we need wait for approval from TB.
