### ISSUE TITLE
Poor contrast in mail Header and locks in calendar tab

### ISSUE THREAD

**Issue by Rosmaninho** [conema/monterail-fulldark#12]
Hello again conema!!

Monterail full-dark is nearly perfect right now. :)
I just wanted to bring this to your attention.

![monterail full dark](https://user-images.githubusercontent.com/42737369/46859111-c0860600-ce04-11e8-92f0-71a2a1615bcc.png)

Would it be possible to put the "X more" test in the mail headers in white color instead of black?

And also the lock for read-only calendars in the calendar tab?

All the best!

**Comment by conema** [comment]
Hi @Rosmaninho, I'll leave this issue open with the [hacktoberfest](https://hacktoberfest.digitalocean.com/) label for a little before fixing it myself, I'll like to find some new contributors

**Comment by Rosmaninho** [comment]
Cool, no problem.

By the way did anyone ever got into contact with you to improve Thunderbird design?
After this work you really deserve that.

**Comment by conema** [comment]
> By the way did anyone ever got into contact with you to improve Thunderbird design?

I don't know that that will ever happen, I think I should contact them with some proposals, but, unfortunately, I don't have much inspiration :(

**Comment by conema** [comment]
The bug with the black "x more" is resolved with the last update. I'll resolve the one with the lock a soon as possible!

**Comment by Cri85** [comment]
I think the main grey bar is really too light.

![immagine](https://user-images.githubusercontent.com/36699482/48293503-b85ecc00-e47f-11e8-9a36-f8359be49bb0.png)

Maybe something like this?

![immagine](https://user-images.githubusercontent.com/36699482/48293556-0378df00-e480-11e8-9d96-8f95274c3b8c.png)

**Comment by Rosmaninho** [comment]
I don't agree with changing the gray of the main bar. I like it like that, plus that's the color that was defined in the Monterail Full Dark theme in which this one is based.

**Comment by conema** [comment]
> 
> 
> I think the main grey bar is really too light.
> 
> ![immagine](https://user-images.githubusercontent.com/36699482/48293503-b85ecc00-e47f-11e8-9a36-f8359be49bb0.png)
> 

That white bar shouldn't be there, could you explain me how to open it?

**Comment by Cri85** [comment]
> 
> 
> > I think the main grey bar is really too light.
> > ![immagine](https://user-images.githubusercontent.com/36699482/48293503-b85ecc00-e47f-11e8-9a36-f8359be49bb0.png)
> 
> That white bar shouldn't be there, could you explain me how to open it?

![immagine](https://user-images.githubusercontent.com/36699482/48300908-88e2aa80-e4e5-11e8-8f89-7dbbbd6ffa83.png)

For english people, sorry my TB is in italian.

**Comment by conema** [comment]
Hi @Cri85, I have been busy these days, but I managed to fix your problem with the last commit, hope you'll like it!

![immagine](https://user-images.githubusercontent.com/12801153/48660680-079b9280-ea66-11e8-9a85-bfd00a1c1cd0.png)

**Comment by conema** [comment]
Lock fixed too
![immagine](https://user-images.githubusercontent.com/12801153/69328608-d1cc5380-0c4f-11ea-80e7-4b6a5b7dc110.png)
