### ISSUE TITLE
White attachments panel

### ISSUE THREAD

**Issue by Leny1996** [conema/monterail-fulldark#14]
Hi, I've noticed that attachments panel is while, while on default dark theme it's dark.
Now:
![image](https://user-images.githubusercontent.com/8152038/47039954-662ed180-d185-11e8-84ab-cc5cae6dc848.png)
After mouse hover:
![image](https://user-images.githubusercontent.com/8152038/47039982-78107480-d185-11e8-882b-aa95b425cafc.png)
How it should look:
![image](https://user-images.githubusercontent.com/8152038/47040083-b443d500-d185-11e8-9b02-dffe9bef8471.png)
I'm using Mint (Cinnamon) and dark theme.
My TB version is 60.2.1

**Comment by conema** [comment]
Hi Leny, I confirm this, nice catch! I'll leave this issue open for a little for hacktoberfest, but, anyway, this will be fixed in the next update (next week).

**Comment by danherrero** [comment]
Hello, I'd like to take a stab at fixing this!

**Comment by conema** [comment]
Nice to see you here, feel free to make a PR when you're ready. I'd like to help you in some way (thunderbird theming is not very documented), but I'm really busy this two days, but, anyway, ask whatever you want, I'll answer this weekend.

PS: I wrote a mini guide a little time ago, maybe it can help you -> [here](https://github.com/conema/monterail-fulldark/issues/4#issuecomment-421301345)
PS 2: If you understand how it works, it would be a very nice thing if you write a contributing guide with some hint for theme development, this would count how 2 PR (one here and one in the monterail dark version).

**Comment by danherrero** [comment]
Thank you for that mini guide, it was very helpful. Assuming I've understood everything correctly, I'd definitely like to keep contributing and would be interested in working on a contributing guide. 

Thanks again!

**Comment by conema** [comment]
Update is out, we need wait for approval from TB.
