### ISSUE TITLE
no issue, just thanks

### ISSUE THREAD

**Issue by stefangweichinger** [conema/monterail-fulldark#18]
Just a quick thanks for your work and improvements, I really appreciate it. Is it enough to update the theme via the "internal addon update" or do I have to install/update somehow manually to keep up to date with this project?

**Comment by conema** [comment]
Hi @stefangweichinger, thanks for your nice words! You can update the theme directly from the "internal addon update" or with the manual procedure. The main difference between the two ways is that the manual update have all the new fixes (es: #8 #14), while automatic updates are released with a two weeks span. However, I'd advise to use the automatic update features and use the manual one only if there are some major problems with the "older" version available with automatic update.

I'm closing this issue, if you have any other question, you can comment this same issue or open one new.
