### ISSUE TITLE
Monterrail not dark

### ISSUE THREAD

**Issue by stephenaustin** [conema/monterail-fulldark#2]
This theme does not change TB 60 to 'dark.' 
<img width="1920" alt="screenshot 2018-09-02 16 03 14" src="https://user-images.githubusercontent.com/33739991/44953717-c0bbe900-aec9-11e8-8893-597269c01d1c.png">

**Comment by conema** [comment]
Hi @stephenaustin! Did you tried the "Installation fail/Theme didn't change in Thunderbird 60" method listed in the FAQ?

**Comment by stephenaustin** [comment]
Thanks for replying Conema. I indeed tried that method advised in the FAQ, and went to the "extensions" folder. I could not see any file there named "MonterailFullDark@conema.me". So I am unable to try this fix. The only files there are the following. 

> 

 Directory of C:\Users\steph\AppData\Roaming\Thunderbird\Profiles\la5wfi0q.default\extensions

02-Sep-18  03:55 PM    <DIR>          .
02-Sep-18  03:55 PM    <DIR>          ..
30-Aug-18  09:44 AM           338,791 gContactSync@pirules.net.xpi
02-Sep-18  03:54 PM           615,579 MonterailFullDark@conema.me.xpi
30-Aug-18  01:55 PM           768,953 quickfolders@curious.be.xpi
30-Aug-18  09:08 AM           272,024 {58D4392A-842E-11DE-B51A-C7B855D89593}.xpi
30-Aug-18  08:42 AM         4,953,445 {e2fda1a4-762b-4020-b5ad-a41df1933103}.xpi
               
Any other suggestions welcome, thanks.

**Comment by conema** [comment]
No problem! I'm happy that it worked!
