### ISSUE TITLE
2.toolbar

### ISSUE THREAD

**Issue by house67** [conema/monterail-fulldark#21]
first of all it's a great theme, especially since the new Version 1.1.4.
There is only one thing, the 2.toolbar ist still in white, that means you can't seen the text and hardly can seen the icons. Hope you are able to change this in the near future. Tks & brgds
![2 toolbar](https://user-images.githubusercontent.com/44371934/47300422-b6da7a80-d61c-11e8-89bf-9c2a6a3bf6c1.JPG)

**Comment by conema** [comment]
Hi @house67, I didn't know that, it'll be surely be fixed in the next version!

**Comment by conema** [comment]
Resolved with the last commit, I'll leave this issue opened until the released of the next version (3 nov).

**Comment by conema** [comment]
Pushed for automatic update, waiting for approval (few days).

**Comment by house67** [comment]
tks, Looks great now.
