### ISSUE TITLE
Light grey color on the Mail Toolbar...

### ISSUE THREAD

**Issue by DXNWO** [conema/monterail-fulldark#22]
Can the light grey color on the Mail Toolbar and the light grey color when composing a new message be changed to a darker color?  Such as, the dark color in the built-in dark theme (see screenshots).  Thanks.

![image](https://user-images.githubusercontent.com/44730150/47954688-68ee3c80-df63-11e8-9bd1-b874626eaec5.png)

![image](https://user-images.githubusercontent.com/44730150/47954766-938cc500-df64-11e8-9834-89b77f015278.png)

**Comment by conema** [comment]
Hi @Cri85, I saw that you are a graphic designer, I would thank you if you could find some time for create a new palette for the theme!

**Comment by Cri85** [comment]
> 
> 
> Hi @Cri85, I saw that you are a graphic designer, I would thank you if you could find some time for create a new palette for the theme!

Yes, I can do it, but I have no idea how works the theme customization...

**Comment by conema** [comment]
The real problem is that with the new version of TB, full themes will stop working (see #23), so, at the moment, I don't know if it's a clever thing to continue to develop this theme.

**Comment by CountQuadula** [comment]
Monterail Full Dark + TB 60.3.0
This is a nice design except for the "light grey" header.
I've seen hints that this can be edited, but no tutorial. Please link detail instruction on how to change the color to darker grey. Thanks!
**To help others**
>  Go to the "extensions" folder, here there should be a file named "MonterailFullDark@conema.me.xpi"
* While Thunderbird is opened in background, delete the "MonterailFullDark@conema.me.xpi" file.
* This file would not delete while TB was open. A workaround is to Drag the file to the Desktop, then Delete it.

**Comment by conema** [comment]
> 
> 
> Monterail Full Dark + TB 60.3.0
> This is a nice design except for the "light grey" header.
> I've seen hints that this can be edited, but no tutorial. Please link detail instruction on how to change the color to darker grey. Thanks!
> 

Open with a zip/rar tool the file named "MonterailFullDark@conema.me.xpi", that is located into "extension" folder (TB must be closed). Open chrome/MonterailOverlay/css/root.css and edit the 17th row that should have --background-color-light: #838689;, change #838689 with the color that you want. Save the file & start TB.

> **To help others**
> 
> > Go to the "extensions" folder, here there should be a file named "[MonterailFullDark@conema.me.xpi](mailto:MonterailFullDark@conema.me.xpi)"
> > While Thunderbird is opened in background, delete the "[MonterailFullDark@conema.me.xpi](mailto:MonterailFullDark@conema.me.xpi)" file.
> 
> This file would not delete while TB was open. **A workaround is to Drag the file to the Desktop, then Delete it.**

That depends from the OS, but yes, in Windows the file can't be deleted while TB is opened.

**Comment by DXNWO** [comment]
Hello Conema, thanks for the information.  I was able to change the the light grey on the Mail Toolbar to a darker color with the instructions you provided (see below). 

![mont1](https://user-images.githubusercontent.com/44730150/48424754-47463f80-e731-11e8-9c6e-f039f51a145a.jpg)

**Comment by DXNWO** [comment]
Once again, thanks for the information.  I noticed an odd font color change after making the change from earlier.  I need to elaborate, the font color changes in the “To” and “Subject” fields.  If either those fields are selected the text color is white but if neither are selected then the text turns black.  This makes it hard to see with the dark color change previously described.  See screenshots below, thanks again.

![mont2](https://user-images.githubusercontent.com/44730150/48426048-03086e80-e734-11e8-86c0-d80aec6d441e.jpg)

![mont3](https://user-images.githubusercontent.com/44730150/48426098-1582a800-e734-11e8-956c-7abde232c19e.jpg)

**Comment by conema** [comment]
> 
> 
> Once again, thanks for the information. I noticed an odd font color change after making the change from earlier. I need to elaborate, the font color changes in the “To” and “Subject” fields. If either those fields are selected the text color is white but if neither are selected then the text turns black. This makes it hard to see with the dark color change previously described. See screenshots below, thanks again.
>

Resolved with the last commit, remember that if you update the theme, you should re-edit the root.css file. Let me know if all is okay.

PS: Open a new issue if you have any other issues.

**Comment by CountQuadula** [comment]
I have the same issue. How to fix the black text?
"Resolved with the last commit" what does that mean?

**Comment by DXNWO** [comment]
Hello Conema, thank you for updating the compose.css.  Font/text color is good now in the To & Subject fields, great job.

**Comment by CountQuadula** [comment]
Download is 617kb, but TB is giving error"won't install because the file is corrupt".

**Comment by conema** [comment]
> 
> 
> Download is 617kb, but TB is giving error"won't install because the file is corrupt".

May you send me a screenshot of the .xpi content?

**Comment by CountQuadula** [comment]
Screenshot of TB
![tb_addon](https://user-images.githubusercontent.com/42452955/48582861-4fe27580-e8eb-11e8-8081-4c27735517e6.jpg)

**Comment by conema** [comment]
@CountQuadula The update is being released with automatic update, so you can wait for it, just a one/two day!

**Comment by CountQuadula** [comment]
Thanks Conema, Apologies, I clearly misunderstood the instructions. This is not something I typically work on. Thanks for your patience.

**Comment by CountQuadula** [comment]
The main (root) window is still blaring white, what controls that color?
![tb_main](https://user-images.githubusercontent.com/42452955/48662733-c1393a00-ea4b-11e8-8a65-0c5524f53017.jpg)

**Comment by conema** [comment]
> Thanks Conema, Apologies, I clearly misunderstood the instructions. This is not something I typically work on. Thanks for your patience. Now that i've edited the color to: #090909, it looks great! Thanks for the fix.

No problem!



> The main (root) window is still blaring white, what controls that color?

This can't be done by changing some theme variable like last time, you should change the background/text color of the `#acctCentralGrid` container with CSS. Something like 
`#acctCentralGrid {
  background-color: #some-color;
  color: #some-color;
}`

**Comment by CountQuadula** [comment]
Haha, Yea, I'm lost already. Where is "#acctCentralGrid container "?

**Comment by conema** [comment]
> Haha, Yea, I'm lost already. Where is "#acctCentralGrid container "?

Open the same file as before, `root.css`, go at the end of the file, after the last `}` and paste this: `#acctCentralGrid { background-color: #some-color; color: #some-color; }`. Remember to change `#some-color`, with the color that you want. Save the file and do the same thing that you did for changing the other color (zip, xpi, etc...).

PS: If you want more help to learn of to tweak things, you should go to [mozillazine](http://forums.mozillazine.org/), a forum about this sort of things

**Comment by CountQuadula** [comment]
There are two "#some-color;" Do they need to be the same Color?
e.g.
`}
#acctCentralGrid { background-color: #090909r; color: #090909; 
}`

**Comment by conema** [comment]
> There are two "#some-color;" Do they need to be the same Color?
> e.g.
> `} #acctCentralGrid { background-color: #090909r; color: #090909; }`

Nope, "background-color" is for the background, "color" is for the text color

**Comment by CountQuadula** [comment]
Here is the last two code lines, I've tried it with "} ." and without "." with no change. 
`#facet-date text {
    fill: var(--headers-background-color);
}

/* TB Mail Main Screen */
#acctCentralGrid { 
	background-color: #363636; color: #838689;

}`

**Comment by conema** [comment]
> 
> 
> Here is the last two code lines, I've tried it with "} ." and without "." with no change.
> `#facet-date text {
> fill: var(--headers-background-color);
> }
> 
> /* TB Mail Main Screen */
> #acctCentralGrid {
> background-color: #363636; color: #838689;
> 
> }`

Mhmh, I think that it's better to put this code into [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css&printable=yes), but it's a thing that doesn't concern the theme, so you would find more useful to open a thread on mozillazine to ask for help!

**Comment by conema** [comment]
I changed the color in the last commit (after a long time)
