### ISSUE TITLE
Compatibility with > 60.0.x

### ISSUE THREAD

**Issue by cookieguru** [conema/monterail-fulldark#23]
I'll glady help with this, but so far I've been unable to find any documentation from Mozilla on how themes work past 60, nor have I found any themes that do anything beyond add a picture behind the tab bar.

**Comment by conema** [comment]
Hi @cookieguru, for the moment there aren't compatibility issue with 60.x, however, help is always welcomed. I know that the documentation about themes development is practically non-existent,  [I wrote a mini-guide](https://github.com/conema/monterail-fulldark/issues/4#issuecomment-421301345) a while ago, I hope that this will help you, but you'll learn only if you play a little around.

I'm closing this, but if you need help, feel free to add a comment.

**Comment by cookieguru** [comment]
I'm not referring to 60.0.x, but rather versions greater than that, as the title indicated.

Installation in 64.0b1 is not possible, even after modifying `install.rdf` to allow for a `maxVersion` > 64.

![screenshot](https://user-images.githubusercontent.com/1888809/48049638-188a0100-e154-11e8-96dd-b6a5ee00bc82.png)

As the screenshot shows, Legacy extensions must be updated to be compatible with Thunderbird 64.0.  [The link](https://support.mozilla.org/en-US/kb/unable-install-add-on-extension-theme-thunderbird) unfortunately has information directed at end users trying to install extensions instead of developers, so I'm unsure what steps need to be taken to make this theme compatible with versions newer than 60.

**Comment by conema** [comment]
Oh, I misunderstood you! I'll give a look at your link and I'll update the theme as soon as possible!
Reopened.

**Comment by conema** [comment]
So, I went in the IRC dev channel of Thunderbird and Paenglab told me that full themes **will not be supported** after TB 60.x, so we can't port this theme (and others) to the new versions of TB. We could try to re-implement the theme with WebExtension, but it's a new thing that doesn't not offer the same "API" of the old methods... I can say that this issue we'll be a no-fix for the moment.

**Comment by cookieguru** [comment]
Is it possible to use CSS in the newer versions?  That way the interface could be styles fairly easy with DOM Inspector, if that or something else got updated to work too

**Comment by Rosmaninho** [comment]
Well, I guess I'll stick to Thunderbird 60 then.

**Comment by conema** [comment]
> 
> 
> Is it possible to use CSS in the newer versions? That way the interface could be styles fairly easy with DOM Inspector, if that or something else got updated to work too

Yes and no: with new version is not possible to create full theme as addons, but I think that we could use the old way, with userChrome.css (like the original spymastermatt's version). The main problem is that with userChrome.css, tweaking is not very easy for end users (At the moment there are 5 version of the same theme: 2 for version >60 and <60 and 3 for Win/Linux/OSX, with the addon, TB _choose_ the best version for the user), I'll see if there is someway for continue to use the addon.

> 
> 
> Well, I guess I'll stick to Thunderbird 60 then.

Positive thing: the next stable version will be the 68, we have some time for find a solution.

**Comment by conema** [comment]
Ok just for update you, I'm currently working on porting the Dark version to TB >68, I will do it for this version too as soon as possible.

[Related issue](https://github.com/conema/monterail-dark/issues/31)

**Comment by conema** [comment]
Here the extension for tb >68 with the full dark theme, the file should be renamed as monterail-fulldark-2.xpi and installed via TB.
[monterail-fulldark-2.zip](https://github.com/conema/monterail-fulldark/files/3860347/monterail-fulldark-2.zip)

**Comment by conema** [comment]
Here the download from the addons website: https://addons.thunderbird.net/it/thunderbird/addon/monterail-full-dark-2/
