### ISSUE TITLE
Install question

### ISSUE THREAD

**Issue by GormCh** [conema/monterail-fulldark#25]
I found the info not fully clear.
To use the theme I assume it has to be installed ín the normal way. Then the packaged named "thunderbird-monterail-master.zip" should be extracted, re-named to chrome and placed in the Thunderbird folder.

Are there any other settings, apart from selecting the theme in the Thunderbird Add-on section? 
I ask because changes I did in the userChrome.css. The theme starts up ok.

Gorm

**Comment by conema** [comment]
> Then the packaged named "thunderbird-monterail-master.zip" should be extracted, re-named to chrome and placed in the Thunderbird folder.

That shouldn't be done. Maybe are you following the guide for install the old version of the theme? This one can be installed directly from the Thunderbird Add-on section or with the .xpi file.

> Are there any other settings, apart from selecting the theme in the Thunderbird Add-on section?

There aren't other settings, editing the userChrome.css is the fastest way.

**Comment by GormCh** [comment]
I downloaded the zip from Github and followed the instructions in readme.md.
The theme is very good but I's to make some changes because of my vision problems. I thought i would be possible with the additional zip file.

**Comment by conema** [comment]
The fastest way is to edit the [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css&printable=yes) like I think you did, all the changes that you made there, should be overwrites the theme ones. 
Another way is to edit the root.css file located in `chrome/MonterailOverlay/css/`, that file contains all the variables that you can edit for change the font color/dimension, but is a little more complicated procedure.

> followed the instructions in readme.md.
>> Then the packaged named "thunderbird-monterail-master.zip" should be extracted, re-named to chrome and placed in the Thunderbird folder.

These information are not written in the readme of this theme, they were written in the theme version of spymastermatt. 
For install this theme you can do one of these two things:

1. Install the theme through the extension page in thunderbird (easier and fastest way)
2. Download the zip from the repository, unzip it and create a new zip with its contents (when you unzip the file, a folder called "monterail-fulldark" will be created, you should create a new zip with the files that are into this folder, so the zip should contain: chrome, LICENSE, README.MD, chrome.manifest, icon.png, install.rdf and preview.png. Rename this zip to `monterail-fulldark.xpi` and install it trough the addons page of thunderbird (with manual installation)

If you need more help, I could help you to make the edits that you want, but I'll be free only this weekend.

**Comment by GormCh** [comment]
Followed your advice. Thank you very much!
Works like charm!

Gorm

**Comment by conema** [comment]
I'm happy to hear that, I'll close this issue, if you have other problems, just comment again!
