### ISSUE TITLE
Darken blue bars in the calendar tab

### ISSUE THREAD

**Issue by Philipp0205** [conema/monterail-fulldark#26]
Hey,
the darkmode is nearly perfect and I really like the look & feel.
There is one little thing which could be improved. There are blue bars in the calendar tab which do not fit in the darkmode.

![grafik](https://user-images.githubusercontent.com/36603238/55277297-cf9f3880-52fe-11e9-9260-7c9c8263151f.png)

Is it possible to change this?
Thank you!

**Comment by conema** [comment]
Hi Philipp,
The fastest way to accomplish this is to change the color of the `--tree-background-color-selected` variable that you can find in the 21th row in `chrome/MonterailOverlay/css/root.css`. But, by changing this variable I think that you'll change also other colors that are not used only on the calendar (it will change also the selected color on the mail list).
The other slower method, is to find and change all the color definitions in the css file, that indeed change the color only in the calendar. I think that you'll need to change these `files:rows`:

- monterailoverlay/css/messenger.css:544
- monterailoverlay/css/messenger.css:584
- monterailoverlay/css/messenger.css:599

Happy hacking, let me know if you need further help!

**Comment by Philipp0205** [comment]
Thank you for your answer! I cannot find any root.css file in the Thunderbird chrome folder. Do I have to do something else for it?

Thank you!

**Comment by conema** [comment]
My pleasure! 
The files that I said can be found in:

- **Windows**: C:\Users\ [your windows user]\AppData\Roaming\Thunderbird\Profiles\[(literally) random letters and numbers].default/extensions/MonterailFullDark@conema.me
- **Linux**: /home/[your linux user]/.thunderbird/[(literally) random letters and numbers].default/extensions/MonterailFullDark@conema.me
- **MacOS**: /home/[your macos user]/Library/Thunderbird/Profiles/[(literally) random letters and numbers].default/extensions/MonterailFullDark@conema.me

The `MonterailFullDark@conema.me` is an archive, so it can be opened with an archive tool.
Remember that Thunderbird needs to be closed to edit the files that are stored into the archive.

**Comment by Philipp0205** [comment]
Oh, did not realise it was an archive. That was the information I needed. Thanks again!
