### ISSUE TITLE
Message view is white

### ISSUE THREAD

**Issue by qazip** [conema/monterail-fulldark#27]
Would it be possible to have the message view (as in, the place where an email's text appears) dark as well? It currently is white.

**Comment by conema** [comment]
Yes, it's possible, but it's a Thunderbird setting. You need to go in: Tools -> Display -> press the "colors" button -> change text/bg color

PS: note that you can change only the bg of "pure text email", email sent with HTML have they own background color that overwrite the default one.

![immagine](https://user-images.githubusercontent.com/12801153/55795282-b13bf880-5ac7-11e9-930b-c6ea2269119f.png)

**Comment by qazip** [comment]
Thank you!
