### ISSUE TITLE
Hard to see Unread emails

### ISSUE THREAD

**Issue by qazip** [conema/monterail-fulldark#28]
It would be better (imo) if there was an higher contrast between read and unread e-mails. As it is, I have some trouble in differentiating read and unread e-mails. Perhaps a different foreground color?

There is the green read-icon thingie, but something feels wrong. Maybe it's just that I am not used to thunderbird.

EDIT: Would it be possible to change the size of the green circle for unread items?

**Comment by inakimalerba** [comment]
Just installed this theme and its awesome, but I find this point quite important. 

Already edited the listing height but this is beyond my css abilities :stuck_out_tongue: .

**Comment by qazip** [comment]
Ya, I would also like the listing height to be a little larger. Also, is it possible to increase the height of the folders? @conema

**Comment by conema** [comment]
>  I would also like the listing height to be a little larger
Are you speaking about the threadlist (mail list)?

**Comment by qazip** [comment]
> > I would also like the listing height to be a little larger
> 
> Are you speaking about the threadlist (mail list)?

Yes.. That and the height of the folders in the folder list.

**Comment by conema** [comment]
You can increase these heights by changing rows 30 and 31 of the skin/root.css file
![immagine](https://user-images.githubusercontent.com/12801153/70741771-57599580-1d1c-11ea-8813-476150e82af2.png)

For the unread mails, I will test something next weekend and I'll update you.

**Comment by markc** [comment]
FWIW I always add these 2 snippets to my userChrome.css. The first one makes the folder list font-size smaller and the second one changes unread messages to red...
```
#folderTree > treechildren::-moz-tree-cell-text {
  font-size: 0.75em;
}
#threadTree > treechildren::-moz-tree-cell-text(unread) {
  color: #EF0000 !important;
  font-weight: normal !important;
}
```

**Comment by N6REJ** [comment]
> It would be better (imo) if there was an higher contrast between read and unread e-mails. As it is, I have some trouble in differentiating read and unread e-mails. Perhaps a different foreground color?
> 
> There is the green read-icon thingie, but something feels wrong. Maybe it's just that I am not used to thunderbird.
> 
> EDIT: Would it be possible to change the size of the green circle for unread items?

thats my "show-stopper" as well.  I can't easily tell whats new whats not.  Since I keep dozens of emails in a folder at a time this is critical.

**Comment by markc** [comment]
An override fix for showing a different color for unread messages. Go to Preferences/Options -> Advanced -> Config Editor. Search for "toolkit.legacy" and make sure the value of "toolkit.legacyUserProfileCustomizations.stylesheets" is set to "true". Create a "chrome" folder inside your profile folder (Google for different OSs) and create a "userChrome.css" file with the below. Change the "color" value to whatever you want and remove the "font-weight" line if you prefer bold.

```
#threadTree > treechildren::-moz-tree-cell-text(unread) {
  color: #EF0000 !important;
  font-weight: normal !important;
}
```

**Comment by Sheenaah** [comment]
Hi everyone, 

I have a question.

What do I have to do to change the background color of unread mails ?

Here I made you a screenshot example :
- red mail titles (unread)
- black mail titles (read)

![0](https://user-images.githubusercontent.com/66884599/84707704-79e49980-af5f-11ea-92f9-3f2567126ccd.jpg)


Thank you a lot for your help !

**Comment by markc** [comment]
This might get you halfway there in userChrome.css...

```
#threadTree > treechildren::-moz-tree-cell-text(unread) {
  color: #FF0000 !important;
  font-weight: normal !important;
  background-color: yellow;
}
```

**Comment by Sheenaah** [comment]
Hi markc ,

It doesn't work.
I tried also :

```
#threadTree > treechildren::-moz-tree-cell-text(unread) {
  color: #FF0000 !important;
  font-weight: bold !important;
  background-color: #fcff00;
}
```

but nothing changes.

Do you have an idea ?

**Comment by markc** [comment]
Try ...

`background-color: #fcff00 !important;`

**Comment by Sheenaah** [comment]
The color appears but, is it possible to have this result ?


![unread](https://user-images.githubusercontent.com/66884599/84772585-6ecf4f00-afdb-11ea-9216-b37143deb0ec.jpg)

**Comment by markc** [comment]
Sorry, I've tried a few CSS options but I don't know how to select the entire row background and border color for unread messages.

**Comment by Sheenaah** [comment]
Don't apologize.
I opened a new topic for this particular question. Maybe someone will have an idea.

Thank you for your help markc !

**Comment by conema** [comment]
You can change the bg/text of unread emails by adding these lines in userChrome.css or in root.css (the second one is a theme file) by adding:

```
#threadTree > treechildren::-moz-tree-cell-text(unread),
#threadTree > treechildren::-moz-tree-cell(unread) {
    color: yellow !important;
    background-color: red !important;
}
```
