### ISSUE TITLE
replies :: color of quoted text

### ISSUE THREAD

**Issue by stefangweichinger** [conema/monterail-fulldark#29]
At first: thanks for the great theme, I really love it and use it for years(?) now ;-)

What I don't get:

when I reply to an email (= a draft is opened) the colors aren't ideal IMO

the quoted text is in blue, the background is a dark grey and the contrast between the two could be better ... it's hard to read the quoted text and stressful on my eyes.

I am not sure where and how to change that, I played with various settings, toggled system colors etc etc

Maybe this is part of the theme or not, I am quite confident that you guys can point me at the right place to improve that.

thanks, Stefan

ps: will attach screenshot if requested

**Comment by conema** [comment]
Hi Stefan,
Thanks for your kind words! 
You should try to put these lines in userContent.css, change `<color>` with the color which you prefer. 

```
span[_moz_quote="true"] {
  color: <color> !important;
}

pre[_moz_quote="true"] {
  color: <color> !important;
}
```

The userContent.css file should be located into:
- Windows: C:\Users\[your windows user]\AppData\Roaming\Thunderbird\Profiles\[(literally) random letters and numbers].default/chrome/

- Linux: /home/[your linux user]/.thunderbird/[(literally) random letters and numbers].default/chorme/

- MacOS: /home/[your macos user]/Library/Thunderbird/Profiles/[(literally) random letters and numbers].default/chrome/

If you didn't find the chrome folder or the userContent.css file, you need to create them.

**Comment by stefangweichinger** [comment]
> Hi Stefan,
> Thanks for your kind words!
> You should try to put these lines in userContent.css, change `<color>` with the color which you prefer.
> 
> ```
> span[_moz_quote="true"] {
>   color: <color> !important;
> }
> 
> pre[_moz_quote="true"] {
>   color: <color> !important;
> }
> ```
> 
> The userContent.css file should be located into:
> 
> * Windows: C:\Users[your windows user]\AppData\Roaming\Thunderbird\Profiles[(literally) random letters and numbers].default/chrome/
> * Linux: /home/[your linux user]/.thunderbird/[(literally) random letters and numbers].default/chorme/
> * MacOS: /home/[your macos user]/Library/Thunderbird/Profiles/[(literally) random letters and numbers].default/chrome/
> 
> If you didn't find the chrome folder or the userContent.css file, you need to create them.

ah, yes, seems to work ;-) and the background of the draft? If I could change that from grey to something else ...

**Comment by stefangweichinger** [comment]
> ah, yes, seems to work ;-) and the background of the draft? If I could change that from grey to something else ...

solved, thanks
