### ISSUE TITLE
tag colors not applied

### ISSUE THREAD

**Issue by stefangweichinger** [conema/monterail-fulldark#30]
thanks for the new release https://github.com/conema/monterail-fulldark/releases/tag/2.0 !

I use it under Fedora 31 and with the thunderbird-package provided by the fedora repos.

Unfortunately I have to report back that for me the colors of tags aren't visible:

If I tag a message by pressing the respective number key, the message isn't displayed with the assigned color. The tag is attached, but no color.

This happens on both of my systems.

I don't have anything special "userChrome.css" as far as I know ...

pls advise, thanks

**Comment by conema** [comment]
Hi @stefangweichinger, I push a fix to resolve this.

![immagine](https://user-images.githubusercontent.com/12801153/69328244-320ec580-0c4f-11ea-8981-b735a0b039f6.png)

**Comment by stefangweichinger** [comment]
> Hi @stefangweichinger, I pushed a fix to resolve this.
> 
> ![immagine](https://user-images.githubusercontent.com/12801153/69328244-320ec580-0c4f-11ea-8981-b735a0b039f6.png)

nice thanks. How will I get this updated version? Is there a newer release then?

**Comment by conema** [comment]
You should follow the "Manual (from source)" procedure written on the readme. I don't know when the official update will be released, the admins of the thunderbird extensions webpage haven't even accepted the update for the 2.0 version... We need to wait a little

**Comment by stefangweichinger** [comment]
Managed it successfully ;-) 
Wouldn't a small bash script or example help to do that? Just a suggestion.
Ah, and yes: tags are colored now, great!
