### ISSUE TITLE
Installation on Thunderbird 68.2.1/Linux fails

### ISSUE THREAD

**Issue by Jnmattern** [conema/monterail-fulldark#31]
Addon installation on Tunderbird 68.2.1 Linux (Ubuntu 18.04 LTS Desktop) fails, says it's not compatible with this version of thunderbird.

**Steps to reproduce the behavior:**
1. Download 'monterail-fulldark-master.zip'
2. Renamed it to 'monterail-fulldark-master.xpi'
3. Install it using the manual addon 'install from file' procedure of Thunderbird
4. See error on attached image
![Capture du 2019-11-27 10-49-54](https://user-images.githubusercontent.com/4257480/69712928-ebfcaa80-1103-11ea-99a0-66f2af1026b0.png)
Translation is 'This module could not be installed because it is not compatible with thunderbird 68.2.1'.

**Expected behavior**
According to you description, you updated the addon to be compatible with thunderbird 68 so I expected it to be installable.

**Build information (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS 
 - Version: 68.2.1 64bit

**Additional context**
N/A

**Comment by conema** [comment]
Hi @Jnmattern, you should create a zip with the content of the folder into monterail-fulldark-master.zip. So, the zip should contains this folders/files:
![immagine](https://user-images.githubusercontent.com/12801153/69752233-11fc6c00-1151-11ea-8150-1946f56fa7b5.png)

The same zip should be renamed as xpi and installed like you were doing.

**Comment by Jnmattern** [comment]
I'm so sorry I bothered you with this, this seems obvious now!!! I did not understand that the zip archive should have all the files at root level and not in a subdirectory...

It works like a charm now! Thanks a lot for your efforts!!
