### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by qazip** [conema/monterail-fulldark#33]
I installed this theme on thunderbird 68.3.0-1 but it seems like it is not working. Absolutely nothing is changed after installing it... I zipped the contents of the repo to an .xpi, dragged to the addons page and it installed. I have the entry "Monterail Full-Dark" in the extensions page. Yet, nothing is changed.

Any idea what is happening?

EDIT: I tried dragging and dropping to the "Themes" page, instead of the "Extensions" page, but the end result is exactly the same.

**Comment by conema** [comment]
Hi @qazip, did you download the archive from the master (https://github.com/conema/monterail-fulldark/archive/master.zip) and made the .xpi file with only the content of the folder "monterail-fulldark-master"? May you made a screen of the extension page?

**Comment by qazip** [comment]
Yes to all that. 
![monterail](https://user-images.githubusercontent.com/16175716/70713325-ad5b1880-1cdd-11ea-8657-bf16322bb3f6.png)

**Comment by qazip** [comment]
Ah wait. I forgot to add the flag "-r" to the "zip" command, as to add recursively. I am an idiot, my bad!!
