### ISSUE TITLE
doesn't work with 68.3

### ISSUE THREAD

**Issue by N6REJ** [conema/monterail-fulldark#34]
**Describe the bug**
v 68.3 totally barfed theming

windows 10 x64 pro

**Comment by markc** [comment]
I just installed the addon in TB 68.3.1 and it seems okay (Manjaro/KDE)

**Comment by conema** [comment]
I'm with Win10 pro and I didn't have any problem. Did you updated to the 2.1 version?
May you send a screenshot?

**Comment by N6REJ** [comment]
![image](https://user-images.githubusercontent.com/1850089/71448291-bac1cb00-26ff-11ea-93e0-904e692f1b94.png)
you'll see they don't even show that they are installed.  No errors occurred but there is nothing there.

**Comment by N6REJ** [comment]
ok, found it... you have to click on "view recent updates"  and then they show up.
can anything be done to fix the blurry text? ( green circled ) 
![image](https://user-images.githubusercontent.com/1850089/71448443-78998900-2701-11ea-87ff-3197ca0f9505.png)
most of the text is tack sharp but the left side, especially "new" is not.

**Comment by conema** [comment]
> you'll see they don't even show that they are installed. No errors occurred but there is nothing there.
I tried both full dark 2.0 and dark 2.0

Because they're listed under "extension", not in "themes".

> can anything be done to fix the blurry text?

Sadly, I can't change the antialiasing of the font, it is a OS/application configuration.
Maybe you can reach better result with another font, you can change it by editing the skin/root.css file on row 6.

**Comment by N6REJ** [comment]
thanks for the "fix".  I switched to a mobile device universal font "Roboto - Light"  Feel free to use it if you wish.. https://github.com/N6REJ/monterail-fulldark
![image](https://user-images.githubusercontent.com/1850089/71486464-1d889480-27dc-11ea-8559-2b77e818e172.png)
