### ISSUE TITLE
Lightning colors messy with Dark theme

### ISSUE THREAD

**Issue by Leinatan** [conema/monterail-fulldark#35]
Running Thunderbird on Manjaro KDE, with Kvantum and Arc-Dark theme.

I installed the monterrail set of themes, which really is great (fully recommend, gives thunderbird a much more modern look). I only have problems in the lightning extension

![image](https://user-images.githubusercontent.com/21956401/71474991-8709a280-27de-11ea-91fc-6dd86ef91fb0.png)

As you can see in this screenshot, calendar colors are quite messy. The biggest problems are the date selection tools, which are white-text over white background. Not really ideal.

I couldn't figure out how to change this in my UserChrome.css file. Does anybody have an idea?

**Comment by conema** [comment]
Hi Leinatan,
Thank you for having opened the issue here.

Which version of the theme are you using? The last version is the 2.1 and the problem with the calendar should be resolved:
![immagine](https://user-images.githubusercontent.com/12801153/71475678-9807e300-27e1-11ea-87a7-19c5c5b0b823.png)

**Comment by Leinatan** [comment]
Okay so I updated and now it does look much better indeed!

![Screenshot_20191226_155850](https://user-images.githubusercontent.com/21956401/71480401-25a2fd00-27f9-11ea-8271-fffb193d608c.png)

There are still some issues though. Some white background is still left and days separators are missing in the "week" view.

Unrelated question: where could I change the dominant colors values? The idea would be to match arc-dark theme...

Thank you for your responsiveness!

**Comment by conema** [comment]
I can't replicate the white background lines. Did you have something in the userChrome or some plugin that could cause this problem? Did you recognized a pattern in the problem (eg. the lines are present only if there are more than x events in the same hour, etc...)?

> Unrelated question: where could I change the dominant colors values? The idea would be to match arc-dark theme...

Same procedure as [this issue](https://github.com/conema/monterail-dark/issues/38). Remember to take a backup of the root.css, because it's overwritten at every update.

**Comment by Leinatan** [comment]
I hade already deleted my userchrome and all plugins so that wasn't it, but it now works properly anyway! I guess I just had to wait and click here and there (maybe it had something to do with the cache? Although I don't think background colors are stored in the cache...)

Anyway thanks a lot!

**Comment by Leinatan** [comment]
Nothing in the userChrome and no extensions enabled other than lightning and this one of course! But it kind of works after minmizing the window + a few clicks on the white backgrounds....

**Comment by conema** [comment]
Fixed in #57
