### ISSUE TITLE
Broken menu

### ISSUE THREAD

**Issue by conema** [conema/monterail-fulldark#38]
**Describe the bug**
The background of the menu should be dark colored

**To Reproduce (if applicable)**
1. Open the menu
2. Press one option with multiple choice

**Screenshots**
![immagine](https://user-images.githubusercontent.com/12801153/71764417-f15dc980-2ee7-11ea-92c7-8384f9434edb.png)

**Comment by jlcenter** [comment]
I'm having the same issue.

**Comment by conema** [comment]
Fixed in the last commit (Fix for Thunderbird 78.x)
