### ISSUE TITLE
Address Book Menu Toolbar using "Light" Colorscheme

### ISSUE THREAD

**Issue by Stewie410** [conema/monterail-fulldark#39]
**Describe the bug**
The Toolbar colors in the Address Book appear to still be using a light theme for the background/button colors, but with white text.  This appears to be the case on all default themes, and is only occurring with `monterail-fulldark` enabled.

At the time of writing, I've tested the version available on the Thunderbird Addons repository, release 2.1 from this github repository, as well as the current master branch from this repository.

**To Reproduce (if applicable)**
1. Go to "Address Book" from the main GUI

**Expected behavior**
At work, on a similarly setup machine, the Address Book looks and works as expected, though perhaps I'm missing the latest update on that machine?

**Screenshots**
![image](https://user-images.githubusercontent.com/24593067/71938764-7f52e200-317e-11ea-8fcb-bd2fd60a579f.png)
Image 1

![image](https://user-images.githubusercontent.com/24593067/71938778-88dc4a00-317e-11ea-80e2-3256953e774f.png)
Image 2

**Build information (please complete the following information):**
 - OS: Windows 10 Pro x64 1909, Build 18363.535
 - Version [e.g. 60.1b]

**Additional Addons not related to this project**
* [Calendar Tweaks](https://addons.thunderbird.net/en-US/thunderbird/addon/calendar-tweaks/?src=search)
* [DKIM Verifier](https://addons.thunderbird.net/en-US/thunderbird/addon/dkim-verifier/?src=search)
* [Enigmail](https://addons.thunderbird.net/en-US/thunderbird/addon/enigmail/?src=search)
* [FiltaQuilla](https://addons.thunderbird.net/en-US/thunderbird/addon/filtaquilla/?src=ss)
* [ImportExportTools NG](https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/?src=ss)
* [Lightning](https://addons.thunderbird.net/en-US/thunderbird/addon/lightning/?src=search)
* [Provider for Google Calendar](https://addons.thunderbird.net/en-US/thunderbird/addon/provider-for-google-calendar/?src=ss)
* [Remove Duplicate Messages (Alternate)](https://addons.thunderbird.net/en-US/thunderbird/addon/remove-duplicate-messages-alte/?src=ss)
* [ThunderKeepPlus](https://addons.thunderbird.net/en-US/thunderbird/addon/thunderkeepplus/?src=ss)

**Additional context**
I've also tested with only Monterail-FullDark enabled, and all other addons disabled, and see the same results.  Many of the above addons are new additions for me, so at first I was initially under the impression that something was conflicting...however, I'm not seeing this anywhere else in the UI, so it was a little odd to me for that to be the case.  Nevertheless, disabling everything else results in the same issue.

**Comment by conema** [comment]
Hi @Stewie410,
Thank you for the perfect report. I confirm that this is a theme issue and it isn't related to any plugin.

**Comment by derritter88** [comment]
I am only having issues with Contacts.
When I use the regular "Dark" the Contacts are readable - "Full Dark" is just a white box (white font + white background)

**Comment by derritter88** [comment]
I combined both themes: Full Dark & Dark.
The address book now uses the CSS files of Dark while the rest is Full Dark.

**Comment by conema** [comment]
Fixed in the last commit (Fix for Thunderbird 78.x)
