### ISSUE TITLE
small issues on Lightning 

### ISSUE THREAD

**Issue by edouardduliege** [conema/monterail-fulldark#4]
Hi,

First, thanks for a great addon.

I use Thunderbird 60.0 on Fedora 28 64b, DE is Plasma 5.13.4

I think the addon could be improved by working on lightning, the contrast with too much. I would advise to work on the background of the calendar, and also the search bar.

![screenshot_20180912_214307](https://user-images.githubusercontent.com/13505517/45449379-4c592500-b6d5-11e8-8304-f4f54d66a492.png)

Let met know if I can be useful! I have few skills in programming though.

Thanks and have a great day!

**Comment by edouardduliege** [comment]
Hi Emanuele,

no worries, I do understand. Thanks for the feedback.

> Could you be more specific about the searchbar? What is your advice?
dark background and light color for the letters, the way it's done in the
email window is perfect. perhaps a greyish bvackground on the calender
itself.

I can play around and suggest colors for each of the category or item or
whatever it's called. I you tell me which files I should modify and how, I
can definitely play around.

Urbanely yours,

Édouard

--
Édouard Duliège
edouard.duliege@gmail.com


Le jeu. 13 sept. 2018 à 21:24, Emanuele Concas <notifications@github.com> a
écrit :

**Comment by conema** [comment]
> dark background and light color for the letters, the way it's done in the email window is perfect

Are you speaking of the event box? The searchbox is already dark mhmh
![immagine](https://user-images.githubusercontent.com/12801153/45541299-030cf080-b80f-11e8-84d9-f079e513aada.png)



> I you tell me which files I should modify and how

It's muddle, there is very little documentation about that and it's a little difficult to me to explain that to you, but you can definitely learn how stylize all the different part of Thunderbird with a little play around.

The main theme files are located in `chrome/MonterailOverlay/css/`
root.css is the main file, into this file there are the variable definition (I think that they are self-explanatory, for ex:  --background-color define the dark background color). In this file I'm also writing the style for things like, scrollbar, searchbar and calendar/lightning. 
  If you know a little of css, you know also that you need the precise id/class of an object to style it, indeed, the frontend of Thunderbird, is build with a strange html and css. 
  For found the precise id or class, you need to use the Page Inspector, like the one that you can use in a browser. For open that in TB, you have to go to the menu bar (it can be opened with the ALT key, it's the menu with: file, edit, visualize, etc...), click on tools -> development tools -> toolbox of development tool. Now the page inspector should be opened.
The next step is to use the "select element of a page", the one with a little box and a mouse icon.
![immagine](https://user-images.githubusercontent.com/12801153/45542298-c1ca1000-b811-11e8-8276-28bc3e01a1d4.png). Click it and return to the normal TB screen, now you should see that every element of TB is being bordered by red dotted line. Just click the thing that you want stylize, the page inspector should update with the HTML of the thing that you clicked! (ex: If you click the event box a "treechildren" element should be highlighted in the page inspect, for style it, you need to find the first father div that have an id, in this case it's a tree with id "unifinder-search-results-tree", so you can stylize the event box using `#unifinder-search-results-tree treechildren` in root.css).
Now you'll need only to update your theme files and restart TB to see the edits...
[MDN guide for style a tree](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/Styling_a_Tree)
If you need more help, you should open a topic in the [Mozillazine](http://forums.mozillazine.org/viewforum.php?f=50&sid=c6aa8dd2dbeb4bbd1ebab695b84d23d7) forum.

It's the best mini-guide that I can write at the moment, it isn't difficult, you'll need only to play around a little for learn.

**Comment by edouardduliege** [comment]
Thanks, I'll play around and I'll let you know.

Urbanely yours,

Édouard

--
Édouard Duliège
edouard.duliege@gmail.com


Le ven. 14 sept. 2018 à 11:56, Emanuele Concas <notifications@github.com> a
écrit :

**Comment by conema** [comment]
I'm closing this for continue the discussion in @Rosmaninho's issues, that are more specific.

https://github.com/conema/monterail-dark/issues/17
https://github.com/conema/monterail-dark/issues/16
https://github.com/conema/monterail-dark/issues/15
https://github.com/conema/monterail-dark/issues/14
