### ISSUE TITLE
Low contrast, bright font in «customize toolbar» dialog

### ISSUE THREAD

**Issue by Semnodime** [conema/monterail-fulldark#40]
**Description**
The contrast of the font against the background in the «customize toolbar» dialog is too low, as the font is bright and so is the background.

**Steps to reproduce the behavior**
1. Start ThunderBird
2. Right click in the main «menue bar» ![Right click in the main «menue bar»](https://user-images.githubusercontent.com/19511852/72031854-09d63700-328e-11ea-9640-34581f2bc661.png)
3. Choose «customize...»
4. The dialog «customize toolbar» has bright font despite the bright background.

**Expected behavior**
The contrast of the font against the background in the «customize toolbar» dialog should be high enough to allow ease of reading.

**Solution ideas**
- dark font in the dialog
- completely new dialog design to make it look as neat as all the newly themed rest of ThunderBird

**Screenshots**
Low contrast in dialog corner
![Low contrast in dialog corner](https://user-images.githubusercontent.com/19511852/72032069-a39de400-328e-11ea-84f5-5f823d7c271e.png)

**Build information**
 - OS: Windows 10, 64bit
 - ThunderBird: 68.3.1 (32-bit), «release» update channel
 - Monterail-fulldark Version 2.1 (updated 09.01.2020)

**Comment by conema** [comment]
Hi @Semnodime,
Thank you for your report. I see that also the icons of the items are white on white background

**Comment by conema** [comment]
Fixed in the last commit (Fix for Thunderbird 78.x)
