### ISSUE TITLE
Replace brighter grey panels with dark colour

### ISSUE THREAD

**Issue by gilbertohasnofb** [conema/monterail-fulldark#41]
Hi, I really like your full dark theme but I am not a big fan of the brighter grey colour that is used in some elements. An example of this is the window for writing a new email. Currently it looks like this:

![image](https://user-images.githubusercontent.com/5700795/80097317-0166eb00-8563-11ea-8856-ef06811a0168.png)

Is there an easy way of making them look like this?:

![image](https://user-images.githubusercontent.com/5700795/80097331-062b9f00-8563-11ea-84cc-3b1e61d972e8.png)

The same is true for the top panel in both the email and calendar:

![image](https://user-images.githubusercontent.com/5700795/80097653-89e58b80-8563-11ea-91c5-311073050d98.png)

**Comment by conema** [comment]
Hi @gilbertohasnofb, 
You should edit the `--background-color-light` variable in `skin/root.css`. 
Change `--background-color-light: #838689;` with `--background-color-light: #37373b;`

This should change the gray color everywhere, let me know if you encounter some problems.

**Comment by gilbertohasnofb** [comment]
@conema Thank you so much, it does look much better. But would you have some suggestion on how to make the Reply, Reply All, Forward, etc. buttons behave the same as the Tag, Quick Filter, etc. buttons? So that they only show the contour and highlight colour when hoovered. This is because after this change, the buttons look like this:

![image](https://user-images.githubusercontent.com/5700795/80103184-b9989180-856b-11ea-9c58-b73d7673bf57.png)

**Comment by conema** [comment]
I'm not sure if this is gonna work, try it and let me know. You should add to `skin/messenger.css`, something like:
```
.toolbarbutton-1.msgHeaderView-button > .toolbarbutton-menubutton-button {
   background-color: var--background-color-light);
}
```

If that doesn't work try with adding `!important`.

**Comment by conema** [comment]
Yes, it is possible, but I'm waiting to see if themes will be supported in the new Thunderbird version (there's the concrete possibility that they won't be)
