### ISSUE TITLE
Some elements not showing light blue accent colour

### ISSUE THREAD

**Issue by gilbertohasnofb** [conema/monterail-fulldark#42]
Some elements not showing light blue accent colour. The current folder in the folder's pane shows only a dark grey highlight on the selected folder as opposed to the light blue accent colour shown in the screenshots in this repo. Also, the calendar does not highlight the today's date any longer. I am using Thunderbird 68.7.0 (64-bit) and a fresh install.

![image](https://user-images.githubusercontent.com/5700795/80098351-9f0eea00-8564-11ea-88ad-85efea5ef1b6.png)

![image](https://user-images.githubusercontent.com/5700795/80098355-a1714400-8564-11ea-94c8-cd28bb6f497d.png)

**Comment by conema** [comment]
Fixed in the last commit (Fix for Thunderbird 78.x)
