### ISSUE TITLE
Change mail list text color

### ISSUE THREAD

**Issue by Sheenaah** [conema/monterail-fulldark#44]
Hi everyone.

First, I have to say that I'm not fluent in English so please excuse my potential language mistakes.
I'll try to do my best !

Here is my question :

I would like to change the mail list text color of the theme Monterail Full Dark.

I am able to change the mail list background color in root.css (I changed the dark grey color for a white color) but I can not find the line for the mail list text color (I would like to replace it with a dark color because now, I can not read the text...)

Can you help me ?

I joined a screenshot to show my problem.

Thank you a lot for your help.

![1](https://user-images.githubusercontent.com/66884599/84577477-ce034880-adbc-11ea-9e8b-8ddf1a3158a1.jpg)

**Comment by conema** [comment]
Hi @Sheenaah, if you want a lighter version, you can check out the [Monterail Dark ](https://github.com/conema/monterail-dark)version. 

By the way, you can change the text color by adding these lines **at the end** of the messenger.css file. Change #fff with your color.

```
#threadTree > treechildren::-moz-tree-cell-text(untagged),
#threadCols {
    color: #fff !important;
}
```

**Comment by Sheenaah** [comment]
Hi conema !

In fact, I love white mail list theme in Monterail Dark, but I prefer most of the colors of Monterail Full Dark.

I thought that it would be easier for me to keep Monterail Full Dark theme but change only :
- mail list background color
- mail list text color  

I don't have much experience in programing.


I have a (maybe stupid) question :

To change .css in Thunderbird, I do this (I translate from French so words may not be the right ones :
**_Tools > Developer Tools > Debug modules_**

![1 2](https://user-images.githubusercontent.com/66884599/84599255-f8aed900-ae70-11ea-9904-20c76e45878c.jpg)

It opens the modules window and I choose Monterail Full Dark :

![1 3](https://user-images.githubusercontent.com/66884599/84599350-a15d3880-ae71-11ea-9403-1b2725abd811.jpg)


The debug modules windows opens, I go to _**style editor**_ tab. 
This is where I've found _roots.css_

![1 4](https://user-images.githubusercontent.com/66884599/84599479-a8387b00-ae72-11ea-8679-9bff3f2a538c.jpg)


Here is my question :

You tell me to add lines at the end of _messenger.css_ but there are several files named messenger.css.

I tested some of them and it seems that it works in the messenger.css I highlighted in darker pink.

Do I have to do this to other messenger.css ?
Or do I go wrong in my method ?

**Comment by Sheenaah** [comment]
Hi conema,

Thank you for your answer.

In fact, I love the Monterail Dark mail list colors but I prefer most of the colors of the Monterail Full Dark theme.

So, I thought it would be easier for me to just change :
- mail list background color
- mail list text color

(I have a very limited experience in programing...)


-----

About your advice, it perfectly works !

Thank you a lot for your help !
