### ISSUE TITLE
Junk mail icon color still the same (junk or no-junk)

### ISSUE THREAD

**Issue by Sheenaah** [conema/monterail-fulldark#45]
Hi everyone.

I'm not fluent in English so please excuse my potential language mistakes.

I've found a problem with junk mail icon in Monterail Full Dark theme :

![2](https://user-images.githubusercontent.com/66884599/84593623-62b58700-ae4d-11ea-9d84-90b861c29038.jpg)

As you can see on my screenshot, the junk mail icon stays the same, junk or no-junk.

And so, even if I :
- click directly on it (next the mail's title)
- click on "Junk" button
- right click on the mail I want to mark as "junk"

Is it possible to fix this problem ?

Thank you a lot for your help.

**Comment by Sheenaah** [comment]
Hi everyone,

so, nobody have an idea ?

Thank you a lot.

**Comment by conema** [comment]
Hi @Sheenaah, sorry for the delay. The problem should be resolved with the last commit, could you confirm it by doing the manual installation procedure?
