### ISSUE TITLE
Change color of Draft/Send/Junk/Trash icons ?

### ISSUE THREAD

**Issue by Sheenaah** [conema/monterail-fulldark#46]
Hi everyone.

I'm not fluent in English so please excuse my potential language mistakes.

I would like to change the color of :
- "Draft" icon
- "Send" icon
- "Junk" icon
- "Trash" icon

like on this example screenshot :

![3](https://user-images.githubusercontent.com/66884599/84594165-a9f14700-ae50-11ea-8209-725f65d90c9b.jpg)

Do you have an idea of how to do this ?

Thank you a lot for your help !

**Comment by conema** [comment]
Hi @Sheenaah,
You should edit the SVG files that you can find in the icons folder. For example, by changing the `flame_junk.svg` in the 55th line with `style="fill:#00ff00;stroke-width:0"`, you can change the junk icon color to green. By finding the other icons, you should be able to do the same.

**Comment by Sheenaah** [comment]
Hi conema,

Thank you for your answer.

Well, I went inside "skin" > "icons" folder, I managed to change the color of `flame_junk.svg`  and `trash.svg` but I tried with :

> - draft.svg
> - sent_light.svg
> -  sent . svg

the color stay the same for draft and sent icons.

I changed all `fill:#"(random color number)` but nothing changes...


Do you have an idea ?


Thank you a lot for your help.

**Comment by conema** [comment]
You can try to edit draft (row 49) and sent (row 32) icons by chaning the fill color in `skin/icons/css/folder.css`. 
Let me know if it works.

**Comment by Sheenaah** [comment]
It works !
Perfect !

Thank you a lot conema !

**Comment by conema** [comment]
You're welcome!
