### ISSUE TITLE
Unread/Read mails background color

### ISSUE THREAD

**Issue by Sheenaah** [conema/monterail-fulldark#47]
Hi everyone,

I have a question :
is it possible to change unread and read mails background colors ?

Here a screenshot example :

![0](https://user-images.githubusercontent.com/66884599/84760102-dc718000-afc7-11ea-943c-732ab6bfcd85.jpg)

Thank you for your help.

**Comment by Sheenaah** [comment]
Hi everyone,

so, nobody have an idea ?

Thank you a lot.

**Comment by klsgrtx** [comment]
I've edited my userChrome.css to change the color of folders that have unread mail.

/* -- changes the color of folders with unread messages -- */
#folderTree > treechildren::-moz-tree-cell-text(folderNameCol, newMessages-true),
#folderTree > treechildren::-moz-tree-cell-text(folderNameCol, hasUnreadMessages-true),
#folderTree > treechildren::-moz-tree-cell-text(folderNameCol, closed, subfoldersHaveUnreadMessages-true) {
	color: #FF00FF !important;
	font-weight: 900 !important;
	font-style: italic !important;
}

**Comment by conema** [comment]
Hi @Sheenaah,
Sorry for the very late reply. You can change the bg/text of unread emails by adding these lines in userChrome.css or in root.css (the second one is a theme file) by adding:

```
#threadTree > treechildren::-moz-tree-cell-text(unread),
#threadTree > treechildren::-moz-tree-cell(unread) {
    color: yellow !important;
    background-color: red !important;
}
```
