### ISSUE TITLE
Hamburger sub menu is white text with white background

### ISSUE THREAD

**Issue by meetdilip** [conema/monterail-fulldark#48]
**Describe the bug**

When we click the Hamburger menu, we get sub-menus for Addons, Tools etc. In this sub-menu there is a white background and almost white text. It is almost impossible to read them.

**To Reproduce (if applicable)**
1. Go to ' Hamburger Menu'
2. Click on 'Tools / Addons'
3. You will see that both the text and background are of the same colour. Even we hover with mouse there is very small amount of readability

**Expected behavior**

Darker background colour or darker text would be legible. 

**Screenshots**
Add screenshots to help explain your problem.

![Monterail Full Dark bug](https://user-images.githubusercontent.com/6965443/92285010-e5b41e00-ef20-11ea-87e9-98137dfe78c8.gif)

**Build information (please complete the following information):**
 - OS: [e.g. Ubuntu] Ubuntu 20.04.1
 - Version [e.g. 60.1b] 68.10.0 (64 bit)

**Additional context**

**Comment by meetdilip** [comment]
@conema Can you tell me the CSS changes / class which would fix this ? ie, where to change the background colour from white to something else. So that I can change it locally. Thanks.

**Comment by conema** [comment]
Hi @meetdilip, you need to edit:
.panel-header (box header, to change the background and color of the tile)
.panel-subview-body (box content, the one which is white, to change only the bg)
.subviewbutton (text into the box, to change only the text color)

I think that you can add these edits directly in skin/messenger.css

**Comment by meetdilip** [comment]
I just tried in skin/messenger.css. But there is no match for subview or panel-header or any of the 3 classes you mentioned. I am not sure what to do. Thanks.

![brk](https://user-images.githubusercontent.com/6965443/92728394-45318400-f38e-11ea-904d-49d0cd1ea0c6.png)

**Comment by conema** [comment]
Sorry, my previous comment was not very clear, add this code at the end of skin/messenger.css:
```
.panel-header, .panel-subview-body, .subviewbutton  {
    background-color: var(--background-color);
    color: #fff;
}
```

The result should be this one:
![immagine](https://user-images.githubusercontent.com/12801153/92729702-03dfab00-f373-11ea-9640-3186a6036e1c.png)

**Comment by meetdilip** [comment]
Working 100 %. Thanks to you :)

**Comment by conema** [comment]
Just to update you, this bug is fixed in the last commit, which also add the compatiblity for TB 78.x

**Comment by meetdilip** [comment]
Thanks. You are doing great. :+1:

**Comment by conema** [comment]
Sorry if I bother you, I'd like to test the new update before releasing an official update, I saw that you are using Ubuntu. Could you install Thunderbird 78.x and try this new update to see if all is good?

Feel free to open a new issue if you find something that is broken.

Ty a lot.

**Comment by meetdilip** [comment]
Sure. No problem :)

**Comment by meetdilip** [comment]
@conema tried after install 78.2.2. When I search for Monterail, the search results show >68 plus entries, but greyed out. Not able to add to v78.2.2.

**Comment by conema** [comment]
Yep, it's not officially released. You can install it by using this file (to install it, from the addons page you need to click the gear and select "install addon from file") [monterail-fulldark.zip](https://github.com/conema/monterail-fulldark/files/5210837/monterail-fulldark.zip)
