### ISSUE TITLE
Monterail for Mailspring?

### ISSUE THREAD

**Issue by Ansem93** [conema/monterail-fulldark#5]
Hi!
I love this theme but I'm using Mailspring, an other open source mail client.
There is any hope that you'll make it for Mailspring too?

**Comment by conema** [comment]
Hi @Ansem93, I didn't know that Nylas mail was dead, I used it for a while before it stop to be free. Mailspring is the child of Nylas!
However, for the moment I haven't any no plans to port this theme in other mail client. I can not promise you anything, but I'll give him a look.
