### ISSUE TITLE
Address book not readable

### ISSUE THREAD

**Issue by Scoty43** [conema/monterail-fulldark#53]
I am on latest TB 78 and use latest monterail-fulldark 3.1 and i can not read the Adressbook, Can you change this please?

![Zwischenablage-Bild (28 Oktober 2020) (2)](https://user-images.githubusercontent.com/25227541/97413793-83b1dc80-1903-11eb-9cc9-4f8622f21d4c.png)

**Comment by conema** [comment]
Hi @Scoty43, are you using the default, dark or light theme (I'm not speaking about the Monterail Theme, you can check it by going to Tools -> Addons -> Themes)? 
If you active the default theme, does the adressbook work? What if you active the light theme?

**Comment by Scoty43** [comment]
I have this issues with both, Dark and Default. With dark i can see but its also not good.
This is with dark, above with default.

![image](https://user-images.githubusercontent.com/25227541/97446268-8118ac80-192e-11eb-9de3-6b1a37838841.png)

**Comment by conema** [comment]
What about the light theme?  Are you using Windows with the dark mode for apps?

**Comment by Scoty43** [comment]
With light Theme i can read but break other Theme stuff. I use the dark mode on Windows 10.

**Comment by conema** [comment]
Hi @Scoty43, I just fixed this issue, you can download the new version from the master. 

![immagine](https://user-images.githubusercontent.com/12801153/97920035-1b2a8b80-1d59-11eb-8b62-4054dff9ba27.png)

**Comment by Scoty43** [comment]
Great will test tomorrow.

**Comment by Scoty43** [comment]
Its fixed. Thx for the great support.
