### ISSUE TITLE
Preview pane is white/light :-(

### ISSUE THREAD

**Issue by vRobM** [conema/monterail-fulldark#55]
From the TB Options I've set the colors for the background color to black and text to gray, yet the preview pane remains white around the dark email background.

Can that be themed as well?

**Comment by conema** [comment]
Hi @vRobM, could you add a screenshot?

**Comment by vRobM** [comment]
![Mozilla Thunderbird](https://user-images.githubusercontent.com/2704733/98626259-3d984800-2309-11eb-8c8b-1ceffe539c76.png)

**Comment by conema** [comment]
Could I see the entire email?

My preview appears like this with black bg and gray text color:
![immagine](https://user-images.githubusercontent.com/12801153/98670960-cc31b700-2353-11eb-9e80-59e5bd09f68d.png)

Note that if the email you are seeing is an HTML email with a background, that background will overwrite the dark background. E.g. see this meetup email that has a white html bg color:
![immagine](https://user-images.githubusercontent.com/12801153/98671210-3185a800-2354-11eb-8373-0ed5f786cb8b.png)

**Comment by vRobM** [comment]
The email itself is not the problem. The TB window around it is.

**Comment by conema** [comment]
Do you see the same problem on my first screenshot? Are you speaking about the white line below the CC address?

**Comment by vRobM** [comment]
No, the issue is all around the email body. Ie the preview window.
See my screen shot, everything below the gray top area is bright.. it should be darker.

If I drag the preview window all the way to the bottom it disappears, but then there's nothing to preview. Double clicking on email opens a new window which is themed dark properly.

**Comment by conema** [comment]
I can't reproduce this issue, have you tried to disable all the addons and to remove all the customization in the userchrome file (if you have any)?

Also, plese give me a complete screenshot, so I can see with my eyes what is happening

**Comment by vRobM** [comment]
![Mozilla Thunderbird](https://user-images.githubusercontent.com/2704733/98749078-e5b61b80-23b2-11eb-8d6f-51dfa84717d4.png)
Restarted TB, no change. No special edits, Don't know where userchrome file is.

**Comment by conema** [comment]
You are using the "Thunderbird Conversations" addon. This is a bug of that addon and not of the Monterail theme. This are the relative issues on their github repository:

https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1510
https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1550

**Comment by vRobM** [comment]
![Mozilla Thunderbird](https://user-images.githubusercontent.com/2704733/98749078-e5b61b80-23b2-11eb-8d6f-51dfa84717d4.png)
Restarted TB, no change. No special edits, Don't know where userchrome file is.
