### ISSUE TITLE
How can I change the color of the date display?

### ISSUE THREAD

**Issue by Scoty43** [conema/monterail-fulldark#56]
How can I change the color of the date display?  I'd like to use the same blue color as the one that is displayed.

![plfnipfedmoadnil](https://user-images.githubusercontent.com/25227541/98924797-86046100-24d5-11eb-98fb-4da42215275f.png)
![gkhienicckhekdfn](https://user-images.githubusercontent.com/25227541/98924864-9b798b00-24d5-11eb-9a1b-82a3b6fb9d5d.png)

**Comment by conema** [comment]
Hi @Scoty43, try to add this code in the root.css file:

```
#datevalue-label, 
#weekdayNameContainer, 
#monthNameContainer,
#currentWeek-label {
    color: var(--tree-background-color-selected) !important;
}
```

**Comment by Scoty43** [comment]
Great Working and looks great.
