### ISSUE TITLE
Folder list pane and message list pane are not dark in Monterail Full Dark 2 for TB>68

### ISSUE THREAD

**Issue by caedmon-kitty** [conema/monterail-fulldark#61]
**Describe the bug**

**To Reproduce (if applicable)**
1. Install Monterail Full Dark 2 for TB>68 version 3.2.1
2. Restart TB
3. See that the folder list and the message list are not dark.  The test appears to be white (hard to tell) and the background is very light grey (almost white).

**Expected behavior**
I expect to see the background in all panes dark with while text,

**Screenshots**
Add screenshots to help explain your problem.

**Build information (please complete the following information):**
 - OS: Fedora 32
 - Version of them: 3.2.1

**Comment by conema** [comment]
Hi @caedmon-kitty, could you do a screenshot? Did you try to reinstall the theme? Are you using other addons or have you modified the userchrome file? Are you using the default, light or dark theme (OS and thunderbird)?

**Comment by conema** [comment]
I'm closing this issue since OP didn't give futher information about the issue and I think that this is related to issue #63

**Comment by caedmon-kitty** [comment]
Sorry I did not receive notification you had responded on December 14th.  I'll look at issue #63 and try the solution there.
