### ISSUE TITLE
Background of the message header too light color in fulldark

### ISSUE THREAD

**Issue by vladbejenaru** [conema/monterail-fulldark#62]
**Describe the bug**
I use TB 78.5.0 with Monterail FullDark 3.2.1. under Xubuntu with dark theme (greybird-dark). Dark theme is enabled in TB Themes.
I have a problem with the message header from the message preview pane: the background is too bright color, font is white and thus unreadable.
I have no other themes or extensions installed.

**To Reproduce (if applicable)**
1. Enable Dark Theme in TB Add-ons Manager -> Themes
2. Enable Monterail Full Dark in TB Add-ons Manager -> Extensions
3. Select one message in Mail Tab. Header of the message appears as in screen shot below

**Expected behavior**
I expect to have something like in the normal TB Dark theme. Example in the second screenshot.

**Screenshots**
Monterail FullDark:
https://imgur.com/1ruBQK7.png
![1ruBQK7](https://user-images.githubusercontent.com/33312839/104188639-d2a6e280-5419-11eb-86e1-c6aa1a0718d0.png)

Standard TB Dark Theme:
https://imgur.com/vlkvs7n

![Screenshot_2021-01-11_14-27-07](https://user-images.githubusercontent.com/33312839/104188642-d33f7900-5419-11eb-9007-cbdc8fb78ed5.png)
**Build information (please complete the following information):**
 - OS: Xubuntu 20.10
 - Version TB 78.5.0 with Monterail FullDark 3.2.1

**Comment by conema** [comment]
Hi @vladbejenaru, does the gray/white background go away if you use the light theme of Thunderbird or/and if you set the default xubuntu theme?

**Comment by vladbejenaru** [comment]
Hi, unfortunately no improvement with any other combination. I have tried also with other OS themes (Adwaita light and dark, Greybird light and dark), TB Default (goes to OS theme), TB light, TB dark...

**Comment by vladbejenaru** [comment]
I think I know why this is happening: my .thunderbird folder contains the settings from a pre-68 version where I have installed Monterail by copying the "chrome" folder (old install way), and now I have settings from both... I will see how to clean up.

Another question: the message body is not "darkefied" using this new version. Can this be obtained somehow? Thanks!

**Comment by conema** [comment]
Yep, you can do it directly using TB options: Thunderbird menu -> Tools -> Options -> Display -> Formatting tab -> Click the "Color" tab and check the setting for the background color.

[Source](https://support.mozilla.org/en-US/questions/1152702), there are also some screenshots that can guide you

**Comment by vladbejenaru** [comment]
Thanks! This moved in Thunderbird 78 to Thunderbird Menu -> Edit -> Preferences -> General -> Language & Appearance -> Colors. 
Before changing the actual colors for Text and Background I have activated the dark theme and checked here the "Use system colors" and it works. Thanks!

**Comment by conema** [comment]
I'm happy that it worked!

> Thunderbird Menu -> Edit -> Preferences -> General -> Language & Appearance -> Colors.

Thank you for the update, I didn't know it
