### ISSUE TITLE
Menu background color

### ISSUE THREAD

**Issue by explor202** [conema/monterail-fulldark#64]
I like this theme, but I find that none of the toolbar menu background match the rest of the theme. I'm running on Windows 8.1, TB 78.7.1. Can these backgrounds be changed to match the rest of the theme (dark with light font)?
![image](https://user-images.githubusercontent.com/13698250/107285378-ad12f600-6a24-11eb-84c1-e067d71ab69a.png)

**Comment by conema** [comment]
Hi @explor202,
We were discussing about this problem in issue #63. I will release a new update this week which will add the dark background, until then, if you want, you can also download the  updated theme directly from the repository and install it using the manual procedure.

**Comment by explor202** [comment]
@conema Thanks for the reply. I did see the discussion and thought about adding to it, but since the OP OS was Win7 I decided not to. I will wait for the update and see how it looks. Thanks again.
