### ISSUE TITLE
Some font and/or background colors are still too light

### ISSUE THREAD

**Issue by explor202** [conema/monterail-fulldark#65]
The updated theme with dark background menus looks great, but some fonts and backgrounds are still too light. The header and right side mail buttons need to either have a darker background to work the the white text, or they need to have a darker text to work with the light background. 
![image](https://user-images.githubusercontent.com/13698250/108421098-4c40a600-71fa-11eb-93ca-d53e4727cd17.png)

![image](https://user-images.githubusercontent.com/13698250/108421148-5b275880-71fa-11eb-8404-e345d11bdb00.png)

**Comment by explor202** [comment]
This would also apply to the footer/progress bar.

**Comment by conema** [comment]
Hi @explor202,
I think that I will follows the [material design](https://material.io/design/color/text-legibility.html#text-backgrounds) guidelines, thus giving an opacity to light text. I'm a little busy at the moment, so I'm not sure when I will work on this.

**Comment by explor202** [comment]
Hi @conema, I think your idea is a good one. Until you have time to work on it, can you provide steps for me to manually change the color? I'd prefer a darker background for the mentioned sections.

**Comment by conema** [comment]
Try to edit this variable https://github.com/conema/monterail-fulldark/blob/d1c8e3f3e2a6d7bcb477327623311f05cc2b0ad2/content/skin/root.css#L34

**Comment by explor202** [comment]
Thanks. I installed monterail-fulldark using the zip file. Where would the css file be stored? I just searched my PC for it and wasn't able to find it.

**Comment by explor202** [comment]
@conema I just did a fresh install of TB on a different PC, then tried installing the add-on from the zip file. I got the same error, with TB saying the add-on is corrupt. I haven't run into this issue before, any suggestions?

**Comment by explor202** [comment]
Okay, this was user error. I've never edited and saved an add-on before, so I was creating a zip using the incorrect folder structure. I have since added just the files to the zip and it installed correctly. The header section of TB is now a nicer color, I'll work on the footer next. Thanks for the help!

**Comment by conema** [comment]
Changing the background in this line should do it:
https://github.com/conema/monterail-fulldark/blob/d1c8e3f3e2a6d7bcb477327623311f05cc2b0ad2/content/skin/compose.css#L67

**Comment by explor202** [comment]
@conema  That's perfect, thanks!
