### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by meetdilip** [conema/monterail-fulldark#66]
Hi, I am not sure whether you remember, but we have talked before. I volunteered to test the theme on v78. 

I wanted to share a mockup for your consideration. It is supposed to be the frosty glass model. But somehow with the tools I use,  the result is as below. If you feel like using the frost glass effect on v78, this mockup might help to begin with :)

![Thunderbird Glass Only 6](https://user-images.githubusercontent.com/6965443/109230997-cc16d380-77eb-11eb-901c-f2bdf3775975.png)

**Comment by meetdilip** [comment]
I think I improved with a render from 3D

![Thunderbird New 5](https://user-images.githubusercontent.com/6965443/109297992-e89d2500-7858-11eb-96e6-68df1518842e.png)

**Comment by conema** [comment]
Hi @meetdilip,
I remember you. I feel that the frost glass effect idea is too far away from the idea of the monterail themes, but you could try to implement yourself a theme, it will be surely a good exercise

**Comment by meetdilip** [comment]
I will surely try. :)
