### ISSUE TITLE
Request: inbox row height

### ISSUE THREAD

**Issue by jeichberger** [conema/monterail-fulldark#68]
[The add-on's screenshots](https://addons.thunderbird.net/en-US/thunderbird/addon/monterail-full-dark-2/) show an increased row height in the inbox message list, however in Thunderbird I only see the default row height. I remember this used to work in an earlier version of Thunderbird / of the Theme.

By adding this to my userChrome.css, I could restore the row height as in the screenshots:

`
#threadTree > treechildren::-moz-tree-row {
    height: 48px !important;
}
`

My setup: Win 10, Thunderbird 78.10.0, Monterail Full Dark 3.2.3

**Comment by conema** [comment]
Hi @jeichberger,
Have you tried to change the height from the addon settings?

![immagine](https://user-images.githubusercontent.com/12801153/116242816-98621680-a766-11eb-9570-01bbf170bc10.png)

**Comment by jeichberger** [comment]
Oh wow, how could I overlook this… Thanks @conema, this setting is exactly what my line in userChrome.css does.
