### ISSUE TITLE
Request: Toolbar icons to be left-aligned

### ISSUE THREAD

**Issue by masked-shizuma** [conema/monterail-fulldark#70]
Hello,
Thank you for the great extension.
It would be even better if there was an option to adjust the spacing of the icons in the toolbar to be narrower. 
Please support this if possible. 
Applying this extension causes the icons in the toolbar to be spread evenly. I prefer to use the icons packed on the left side.
If you disable this extension, the stretch space you have placed will be enabled and the icons in the toolbar will be left-padded.
If it is difficult to add options, I would like to modify this extension to use it, so please let me know where and how to modify it.

Thank you.

**Comment by conema** [comment]
Hi @masked-shizuma,
I'm not sure about which toolbar you are talking about, could you post a screenshot of it?

**Comment by masked-shizuma** [comment]
Thanks for the reply.
I will post a screenshot so you can check it out.
![Extensions pic_01 enabled](https://user-images.githubusercontent.com/88017100/127213293-a24cf454-267a-4894-87d4-1ec16a03bfbb.jpg)
![Extensions pic_02 disabled](https://user-images.githubusercontent.com/88017100/127213308-af942533-df76-468b-b421-ea018f489205.jpg)
The screenshot above shows the arrangement of the icons in the toolbar when this extension is enabled.
The next screenshot shows the arrangement of the icons in the toolbar when the extension is disabled.
I have inserted a stretchable space between the left and right icon groups. Nevertheless, when I enable this extension, it doesn't left justify.
![Extensions pic_03](https://user-images.githubusercontent.com/88017100/127214910-4e82f672-ce2f-4bb7-a540-75f2351f3d13.jpg)
Please confirm.

Thank you.

**Comment by conema** [comment]
You're welcome!

Try to delete these rows:
https://github.com/conema/monterail-fulldark/blob/d1c8e3f3e2a6d7bcb477327623311f05cc2b0ad2/content/skin/root.css#L91-L94

**Comment by masked-shizuma** [comment]
Thanks for the reply.
I deleted the relevant items as you pointed out, and the layout is now as I want it.
I appreciate your kind support.
![Extensions pic_04](https://user-images.githubusercontent.com/88017100/127227085-3195efa3-ce60-4877-9f57-de8f29dc77f7.jpg)

Thank you.
