### ISSUE TITLE
3.3 little issues with Appointment display

### ISSUE THREAD

**Issue by Scoty43** [conema/monterail-fulldark#73]
display problem with appointments. As you can see, it looks a bit choppy. I use this Code from the previous version where it fit.

#datevalue-label, 
#weekdayNameContainer, 
#monthNameContainer,
#currentWeek-label {
    color: var(--tree-background-color-selected) !important;
}

![image](https://user-images.githubusercontent.com/25227541/129567896-726d1612-5300-4194-9c7b-43ad8b7fb468.png)

**Comment by conema** [comment]
Fixed in the last commit, ty

**Comment by Schrotty74** [comment]
I use lates 3.3 from today and its not fixed.

**Comment by conema** [comment]
You need to download the fixed version directly from the repository and not from the releases
