### ISSUE TITLE
Cannot change or delete the theme

### ISSUE THREAD

**Issue by Drachsi** [conema/monterail-fulldark#75]
I have the latest Thunderbird and installed the Theme. Then I found that the small star is hard to see and would have preferred the new emails folder changed to a different colour.

I deleted the Theme, but it does not delete. I cannot change to a Thunderbird theme, everything is locked. I tried installing again and it will not install. I have tried switching the pc off a few times, nothing changes.

I need your support as soon as possible.

Regards
Drachsi

**Comment by conema** [comment]
Hi @Drachsi,
Could you post a screenshot of the extension page?

**Comment by conema** [comment]
I guess that you resolved, let me know otherwise
