### ISSUE TITLE
Contextual menu color issues: white text on light gray, no folder highlighting on "Move to"

### ISSUE THREAD

**Issue by Ph15** [conema/monterail-fulldark#76]
Great theme! Thanks for the code!
Just a quite annoying bug: in Dark theme, the text of the contextual menu (on right-click) is white on a light gray background and thus unreadable. Also, when I want to move a message to a folder through the "Move to" action in the contextual menu, the folders name is not highlighted when I with my arrows up and down (making it difficult to know which folder I am selecting…). This makes the theme a bit hard to use sometimes or needs me to specify more the folder I'm looking for.

As for the Light theme (that I have tried as an alternative, although I was looking for the Dark one), I cannot see the grouped conversation icon and thus identify if the email has an associated thread…

Is there any fix planned for these issues? Any workaround?

I'm still using the theme because I find the interface waaaay better than Thunderbird's one, but feel a bit frustrated by these pain points!
Looking forward to a fix! Many thanks again!
Phil

![Contextual menu white text on light gray](https://user-images.githubusercontent.com/11819455/132122939-144a0f73-8e63-465f-b699-e8d8b8907cb3.png)
![No folder highlighting on  Move to  option](https://user-images.githubusercontent.com/11819455/132122943-652245ce-11fb-4da4-8845-31f64e494261.png)

**Comment by conema** [comment]
Hi @Ph15,
I cannot replicate your issues. What version of Thunderbird and of the theme are you using? What OS are you using?

**Comment by Ph15** [comment]
Hi @conema!
Thanks for your prompt answer!
I'm running Thunderbird 78.13.0 (64 bits) on MacOS 10.14.6.
Theme version: 3.2.3, released on August, 20th.

**Comment by conema** [comment]
Could you try to update Thunderbird to v91 and see if the issues remain?

**Comment by Ph15** [comment]
Thanks for the prompt to update, I thought I was using the latest version since Thunderbird was showing an "Up to date" message.
Seems to be working alright now, thank you! 🙏

**Comment by conema** [comment]
You're welcome! Let me know if there are other issues

**Comment by Ph15** [comment]
Oh, yes, a small one that I forgot to mention and is still here despite the update: the "Send" icon does not display properly on new message boxes (see attached). Any clue?

[Bug Send icon](https://user-images.githubusercontent.com/11819455/132137335-b505e84d-4507-4fc9-8f75-4e2ed428ccc3.png)

**Comment by conema** [comment]
What do you feel wrong about it? The icon per se is correct, maybe it seems like a placeholder image but it's a little box with a "@" into

**Comment by Ph15** [comment]
Oh, I thought it was a bug or a placeholder, my bad. I still don't see the @ in it though…
I preferred the paper plane, but that's just a matter of preference afterwards! 😉
