### ISSUE TITLE
Cannot delete the Theme

### ISSUE THREAD

**Issue by Drachsi** [conema/monterail-fulldark#78]
The first report was closed, even though I sent screen shots to the email address.

I followed exactly the procedure published to remove the Theme and removed the 
 "MonterailFullDark@conema.me.xpi" file.

The file manager only shows the 3 standard Themes.

The Theme is still active.

I want to totally remove it.

Regards
Drachsi

**Comment by conema** [comment]
> The file manager only shows the 3 standard Themes

You should look in the addon (or Extensions, I don't remember the name in the english version) page:
![immagine](https://user-images.githubusercontent.com/12801153/132298856-2127f436-7f3a-4b77-883e-fefd91c418a7.png)

**Comment by Drachsi** [comment]
I enclose an image showing the Theme is active, and an image showing in the Add-ons Manager where it does not exist.

![theme1](https://user-images.githubusercontent.com/16068970/132305478-ec3784a2-1e41-4790-82c0-5f91997e4ac0.jpg)
![theme2](https://user-images.githubusercontent.com/16068970/132305487-e3c14940-e201-4c37-a3c6-d6a4f6912577.jpg)

**Comment by conema** [comment]
You are in the "themes" page, not in the "extensions" page

**Comment by Drachsi** [comment]
Thank you I missed that. Thought it was a Theme, Now not active. 

Will you consider making new emails change colour, the star is hard to see.or maybe some form of personalisation?

Regards
Drachsi

**Comment by conema** [comment]
You're welcome.
Yep, no problem about that. I'm usually very open to make fix/edits or give ad personam customization.

Are you referring to this stars?
![immagine](https://user-images.githubusercontent.com/12801153/132345516-93b7f226-fc58-4487-9166-4f2d6eb5fccd.png)

**Comment by Drachsi** [comment]
No. The star that shows on the email account when the text is italic, and a message arrives. When I use the basic light Theme, a new email is shown in each account as a new colour. Better than the small star which is hard to see on a dark background.

**Comment by conema** [comment]
Ok noted, I'll close this issue since it's resolved, feel free to open a new one if you need to discuss about something other
