### ISSUE TITLE
Search Tab is not themed.

### ISSUE THREAD

**Issue by Rosmaninho** [conema/monterail-fulldark#8]
![search_tab_not_dark2](https://user-images.githubusercontent.com/42737369/46223059-20cb7100-c34a-11e8-8aa8-0acab0e5b888.png)
![search tab full dark](https://user-images.githubusercontent.com/42737369/46223126-5f612b80-c34a-11e8-994a-52364201103f.png)

The Search tab that shows up when searching for mails is not themed both in Dark and FullDark.
Would it be possible to theme them as well?

All the best!

**Comment by conema** [comment]
PR #9 and PR [#21](https://github.com/conema/monterail-dark/pull/21) should resolve this.

I'll wait a little before pushing the PRs because I need to find out a better way to edit glodaFacetView.css
