### ISSUE TITLE
Question/How-to : Revert the folder icon to the customizable default ones

### ISSUE THREAD

**Issue by MatthieuMuschinowski** [conema/monterail-fulldark#80]
Hi there,

First off, thanks for the add-on, it's very nice! :) 
I've been tinkering a bit with the css files to get the color-scheme more to my liking, and I haven't yet been able to find how to use the regular icons for folders : I usually arrange them with colors for the important ones to pop-out, and given the way you do things it seems like all of them have the same icon... How would I go about reverting to these default icons ? 

![Screenshot from 2021-10-29 14-39-49](https://user-images.githubusercontent.com/7795766/139436173-8ba1353f-fc7f-4564-b2dd-f3e3f36235d1.png)

**Comment by conema** [comment]
Hi @MatthieuMuschinowski,
Sorry for the late answer, did you try to delete this line?
https://github.com/conema/monterail-fulldark/blob/58ec8cca5ed0e0bcab72b46f002eb07b4e2d71ef/content/skin/root.css#L2

**Comment by MatthieuMuschinowski** [comment]
Hi, no worries, there's no rush on this :) 
So deleting this line works, but it also removes all the nice custom icons for the gmail folders... I'm guessing I'd need to modify the imported file then to just remove the one icon for folders, I'll keep it like this for now and dig around another time!

**Comment by conema** [comment]
In theory, deleting these rows should do it:
https://github.com/conema/monterail-fulldark/blob/master/content/skin/icons/css/folder.css#L5-L10

**Comment by MatthieuMuschinowski** [comment]
This is absolutely perfect now, thanks a lot ! :+1:

**Comment by conema** [comment]
You are welcome!
